apiVersion: v1
kind: ConfigMap
metadata:
  name: sportsbetting-config
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ConnectionStrings__Postgres: "Host=postgres;Port=5432;Database=sports_betting;Username=postgres;Password=postgres"
  ConnectionStrings__Redis: "redis:6379"
  AWS__Region: "us-east-1"
  AWS__ServiceUrl: "http://localstack.default.svc.cluster.local:4566"
  AWS__SqsQueueUrl: "http://localstack.default.svc.cluster.local:4566/000000000000/bets-events"
